apiVersion: v1
kind: Service
metadata:
  name: mobile-client
spec:
  type: LoadBalancer
  ports:
    - name: "5012"
      port: 5012
      targetPort: 5012
  selector:
    io.kompose.service: mobile-client
